# Site settings
title: "WFP UI Guidelines"
email: "me@matthewmorek.com"
description: ""
url: "https://cdn.wfp.org" # WFP CDN
version: "v0.15.0"
quiet: true

exclude: ["*.sublime-*", "*.sh", "*.yml", "*.DS_*"]

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

category-list: ["Basics", "Components", "Patterns", "Resources", "Info"]

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
